spring:
  application:
    name: sb01-deokhugam-team07
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    open-in-view: false # OSIV 끔

# 로깅 레벨 설정
logging:
  level:
    root: info

# 액츄에이터
management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, loggers
  info:
    env:
      enabled: true

deokhugam:
  storage:
    type: local # local | s3
    local:
      root-path: src/main/resources/static/storage
