name: Run Tests

on:
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: JDK 설정
        uses: actions/setup-java@3.13.0
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle
          
      - name: Create storage directory
        run: mkdir -p src/test/resources/static/storage

      - name: Set up application-test.yml
        run: |
          cat > src/test/resources/application-test.yml << EOF
          deokhugam:
            storage:
              type: local
              local:
                root-path: src/test/resources/static/storage
          EOF

      - name: gradlew 권한 부여
        run: chmod +x gradlew

      - name: 테스트 수행
        run: ./gradlew test -Dspring.profiles.active=test

      - name: codecov 확인
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: SB01-Team07/sb01-deokhugam-team07